import 'package:flutter/material.dart';
import 'quiz_system.dart';

// Color constants
const Color kBackgroundColor = Color.fromRGBO(255, 255, 255, 0.1);
const Color kBorderColor = Color.fromRGBO(255, 255, 255, 0.2);
const Color kTextColor = Color.fromRGBO(255, 255, 255, 0.8);
const Color kDeepBlue = Color(0xFF1B4B82);
const Color kOceanBlue = Color(0xFF2C7DA0);
const Color kWhite = Colors.white;

class Quiz {
  final String title;
  final String description;
  final IconData icon;
  final int questionCount;
  final Widget screen;

  const Quiz({
    required this.title,
    required this.description,
    required this.icon,
    required this.questionCount,
    required this.screen,
  });
}

class QuizSectionScreen extends StatelessWidget {
  QuizSectionScreen({super.key});

  final List<Quiz> quizzes = [
    Quiz(
      title: 'Points of Sail Quiz',
      description: 'Test your knowledge about different points of sail and their characteristics.',
      icon: Icons.navigation,
      questionCount: 5,
      screen: QuizSystem(
        title: 'Points of Sail Quiz',
        description: 'Test your knowledge about different points of sail and their characteristics.',
        icon: Icons.navigation,
        questions: [
          Question(
            question: 'Which point of sail is typically the fastest?',
            options: [
              'Close Hauled',
              'Close Reach',
              'Beam Reach',
              'Broad Reach',
            ],
            correctAnswer: 2,
            explanation: 'A beam reach is typically the fastest point of sail because the wind is hitting the boat at a 90-degree angle, providing optimal lift and forward momentum.',
            aiExplanation: 'The beam reach is considered the fastest point of sail due to several factors: optimal wind angle, reduced drag, and efficient sail trim. When sailing on a beam reach, the wind hits the boat at a 90-degree angle, creating the most efficient lift-to-drag ratio. This allows the boat to achieve maximum speed while maintaining stability.',
            nauticalConcepts: 'Points of Sail:\n• Beam Reach: Sailing with the wind at 90 degrees to the boat\n• Close Hauled: Sailing as close to the wind as possible (30-45 degrees)\n• Close Reach: Sailing between close-hauled and beam reach\n• Broad Reach: Sailing with the wind behind the beam\n\nKey Terms:\n• Lift: The force generated by the sails that propels the boat forward\n• Drag: The resistance created by the boat moving through water\n• Sail Trim: The adjustment of sails to optimize performance',
            visualAidType: 'points_of_sail',
            visualAidData: '',
          ),
          Question(
            question: 'What is the typical angle for close-hauled sailing?',
            options: [
              '15-30 degrees',
              '30-45 degrees',
              '45-60 degrees',
              '60-75 degrees',
            ],
            correctAnswer: 1,
            explanation: 'Close-hauled sailing is typically done at an angle of 30-45 degrees to the wind, as this is the closest angle at which a sailboat can effectively sail into the wind.',
            aiExplanation: 'Close-hauled sailing represents the most efficient angle for sailing upwind. At 30-45 degrees, the boat can maintain forward momentum while minimizing leeway (sideways drift). This angle allows the sails to generate maximum lift while maintaining enough airflow to prevent stalling.',
            nauticalConcepts: 'Close-Hauled Sailing:\n• Definition: Sailing as close to the wind as possible\n• Typical Angle: 30-45 degrees from the wind\n• Sail Trim: Taut sheets, flat sails\n• Boat Position: Heeled to leeward\n\nRelated Terms:\n• Leeway: Sideways drift caused by wind pressure\n• Heel: The tilt of the boat caused by wind pressure\n• Stalling: When sails lose lift due to poor angle',
            visualAidType: 'points_of_sail',
            visualAidData: '',
          ),
          Question(
            question: 'Which point of sail typically results in the most heel?',
            options: [
              'Close Hauled',
              'Beam Reach',
              'Broad Reach',
              'Running',
            ],
            correctAnswer: 0,
            explanation: 'Close-hauled sailing typically results in the most heel because the sails are sheeted in tightly, creating maximum wind pressure and leverage on the boat.',
            aiExplanation: 'Close-hauled sailing produces the most heel due to several factors: tight sail trim, high apparent wind speed, and the leverage created by the wind pressure on the sails. The boat heels to leeward as the wind pressure creates a turning moment around the boat\'s center of buoyancy.',
            nauticalConcepts: 'Heel and Stability:\n• Heel: The angle of tilt from vertical\n• Close-Hauled Heel: Maximum due to tight sail trim\n• Stability Factors:\n  - Sail area exposed to wind\n  - Wind pressure on sails\n  - Boat\'s center of buoyancy\n\nKey Terms:\n• Center of Buoyancy: The center of the underwater volume\n• Leverage: The force created by wind pressure on sails\n• Apparent Wind: The wind felt on the boat (true wind + boat speed)',
            visualAidType: 'points_of_sail',
            visualAidData: '',
          ),
          Question(
            question: 'What is the angle when running?',
            options: [
              '90 degrees',
              '135 degrees',
              '180 degrees',
              '225 degrees',
            ],
            correctAnswer: 2,
            explanation: 'Running is sailing directly downwind, which is at an angle of 180 degrees to the wind.',
            aiExplanation: 'Running is the point of sail where the boat is sailing directly downwind (180 degrees to the wind). This is the most downwind point of sail, where the wind is coming from directly behind the boat. While it may seem like the easiest point of sail, it requires careful attention to prevent accidental jibes and maintain proper sail trim.',
            nauticalConcepts: 'Running:\n• Definition: Sailing directly downwind\n• Angle: 180 degrees to the wind\n• Sail Trim: Eased sheets, full sails\n• Safety Considerations:\n  - Risk of accidental jibes\n  - Need for preventer\n  - Reduced maneuverability\n\nKey Terms:\n• Jibe: Turning the stern through the wind\n• Preventer: Line to prevent accidental jibes\n• Sail Trim: Adjustment of sails for optimal performance',
            visualAidType: 'points_of_sail',
            visualAidData: '',
          ),
          Question(
            question: 'Which point of sail is best for making progress upwind?',
            options: [
              'Close Hauled',
              'Beam Reach',
              'Broad Reach',
              'Running',
            ],
            correctAnswer: 0,
            explanation: 'Close-hauled is the best point of sail for making progress upwind, as it allows the boat to sail as close to the wind as possible while maintaining forward momentum.',
            aiExplanation: 'Close-hauled sailing is essential for making progress upwind. While the boat cannot sail directly into the wind, close-hauled allows it to make the most efficient progress windward. This is achieved through a combination of proper sail trim, boat balance, and careful course management.',
            nauticalConcepts: 'Upwind Sailing:\n• Close-Hauled: Best point for upwind progress\n• Tacking: Zigzag course to make ground upwind\n• Sail Trim: Critical for upwind performance\n• Course Management:\n  - Laylines\n  - Tacking angles\n  - Wind shifts\n\nKey Terms:\n• Layline: Line beyond which you can reach a mark\n• Tacking: Turning the bow through the wind\n• Wind Shift: Change in wind direction',
            visualAidType: 'points_of_sail',
            visualAidData: '',
          ),
        ],
      ),
    ),
    Quiz(
      title: 'Wind Direction Quiz',
      description: 'Test your understanding of wind direction and its effects on sailing.',
      icon: Icons.air,
      questionCount: 5,
      screen: QuizSystem(
        title: 'Wind Direction Quiz',
        description: 'Test your understanding of wind direction and its effects on sailing.',
        icon: Icons.air,
        questions: [
          Question(
            question: 'What is the difference between true wind and apparent wind?',
            options: [
              'True wind is always stronger',
              'Apparent wind is affected by boat speed',
              'True wind is imaginary',
              'There is no difference',
            ],
            correctAnswer: 1,
            explanation: 'Apparent wind is the wind felt on the boat, which is a combination of true wind and the wind created by the boat\'s movement. True wind is the actual wind in the environment.',
            aiExplanation: 'Apparent wind is a crucial concept in sailing that combines true wind with the wind created by the boat\'s movement. When a boat is moving, it creates its own wind (headwind) equal to its speed. This combines with the true wind to create the apparent wind that the boat actually experiences.',
            nauticalConcepts: 'Wind Types:\n• True Wind: The actual wind in the environment\n• Apparent Wind: The wind felt on the boat\n• Boat-Generated Wind: Created by boat movement\n\nKey Terms:\n• Headwind: Wind created by forward movement\n• Wind Vector: Direction and strength of wind\n• Relative Motion: Movement in relation to wind',
            visualAidType: 'wind_direction',
            visualAidData: '',
          ),
          Question(
            question: 'How does boat speed affect apparent wind?',
            options: [
              'It has no effect',
              'It only affects direction',
              'It increases apparent wind speed',
              'It decreases apparent wind speed',
            ],
            correctAnswer: 2,
            explanation: 'Boat speed increases the apparent wind speed because it adds to the true wind speed, creating a stronger wind that the boat experiences.',
            aiExplanation: 'Boat speed directly affects apparent wind speed through vector addition. As the boat moves forward, it creates a headwind equal to its speed. This headwind combines with the true wind to create a stronger apparent wind. The faster the boat moves, the stronger the apparent wind becomes.',
            nauticalConcepts: 'Apparent Wind Effects:\n• Speed Addition: Boat speed adds to true wind\n• Direction Change: Apparent wind shifts forward\n• Sail Trim: Must adjust for changing conditions\n\nKey Terms:\n• Vector Addition: Combining wind forces\n• Wind Shift: Change in apparent wind direction\n• Sail Angle: Adjustment for new wind direction',
            visualAidType: 'wind_direction',
            visualAidData: '',
          ),
          Question(
            question: 'What happens to apparent wind when sailing upwind?',
            options: [
              'It becomes lighter',
              'It becomes stronger',
              'It stays the same',
              'It disappears',
            ],
            correctAnswer: 1,
            explanation: 'When sailing upwind, the apparent wind becomes stronger because the boat\'s speed adds to the true wind speed, creating a stronger headwind.',
            aiExplanation: 'Sailing upwind increases the apparent wind strength because the boat\'s forward motion creates a headwind that adds to the true wind speed. This is why sailing upwind often feels windier than sailing downwind, even in the same true wind conditions.',
            nauticalConcepts: 'Upwind Sailing:\n• Apparent Wind: Increases with boat speed\n• Sail Trim: Tighter for stronger wind\n• Boat Speed: Affects wind strength\n\nKey Terms:\n• Headwind: Wind created by forward motion\n• Sail Tension: Adjustment for wind strength\n• Boat Balance: Maintaining stability in stronger wind',
            visualAidType: 'wind_direction',
            visualAidData: '',
          ),
          Question(
            question: 'Which instrument measures apparent wind?',
            options: [
              'Compass',
              'Anemometer',
              'GPS',
              'Depth Sounder',
            ],
            correctAnswer: 1,
            explanation: 'An anemometer measures apparent wind speed and direction on the boat.',
            aiExplanation: 'Anemometers are essential instruments for measuring apparent wind on a sailboat. They typically consist of rotating cups or a wind vane that measures both wind speed and direction. This information is crucial for proper sail trim and navigation.',
            nauticalConcepts: 'Wind Instruments:\n• Anemometer: Measures wind speed and direction\n• Wind Vane: Shows wind direction\n• Display Units: Shows wind data\n\nKey Terms:\n• Wind Speed: Measured in knots\n• Wind Direction: Relative to boat heading\n• Calibration: Adjusting for accuracy',
            visualAidType: 'wind_direction',
            visualAidData: '',
          ),
          Question(
            question: 'How can you determine true wind direction?',
            options: [
              'Using shore-based indicators',
              'Looking at clouds',
              'Feeling the wind',
              'Using GPS',
            ],
            correctAnswer: 0,
            explanation: 'True wind direction can be determined by observing shore-based indicators like flags, trees, or smoke, which are not affected by boat movement.',
            aiExplanation: 'Shore-based indicators provide the most reliable way to determine true wind direction because they are stationary and not affected by boat movement. Flags, trees, smoke, and other stationary objects show the actual wind direction in the environment.',
            nauticalConcepts: 'Wind Indicators:\n• Shore-Based: Flags, trees, smoke\n• Water-Based: Wave patterns, ripples\n• Atmospheric: Clouds, sea state\n\nKey Terms:\n• Wind Indicator: Shows wind direction\n• Stationary Reference: Unaffected by boat movement\n• Environmental Signs: Natural wind indicators',
            visualAidType: 'wind_direction',
            visualAidData: '',
          ),
        ],
      ),
    ),
    Quiz(
      title: 'Tides and Currents Quiz',
      description: 'Test your knowledge about tides, currents, and their effects on sailing.',
      icon: Icons.water,
      questionCount: 5,
      screen: QuizSystem(
        title: 'Tides and Currents Quiz',
        description: 'Test your knowledge about tides, currents, and their effects on sailing.',
        icon: Icons.water,
        questions: [
          Question(
            question: 'What causes tides?',
            options: [
              'Wind and waves',
              'Gravity of the moon and sun',
              'Ocean currents',
              'Atmospheric pressure',
            ],
            correctAnswer: 1,
            explanation: 'Tides are primarily caused by the gravitational pull of the moon and sun on Earth\'s oceans, with the moon having the strongest effect.',
            aiExplanation: 'Tides are caused by the gravitational forces exerted by the moon and sun on Earth\'s oceans. The moon\'s gravity creates two tidal bulges on Earth - one facing the moon and one on the opposite side. The sun\'s gravity also affects tides, though to a lesser extent.',
            nauticalConcepts: 'Tidal Forces:\n• Moon\'s Gravity: Primary cause of tides\n• Sun\'s Gravity: Secondary influence\n• Spring Tides: When moon and sun align\n• Neap Tides: When forces oppose\n\nKey Terms:\n• Tidal Bulge: Rise in sea level\n• Gravitational Pull: Force causing tides\n• Tidal Range: Difference between high and low tide',
            visualAidType: 'tide_cycle',
            visualAidData: '',
          ),
          Question(
            question: 'What is the difference between flood and ebb tides?',
            options: [
              'Flood is incoming, ebb is outgoing',
              'Flood is outgoing, ebb is incoming',
              'They are the same thing',
              'Flood is faster than ebb',
            ],
            correctAnswer: 0,
            explanation: 'Flood tide is when the tide is coming in (rising), while ebb tide is when the tide is going out (falling).',
            aiExplanation: 'Flood and ebb tides describe the direction of tidal movement. Flood tide is the incoming tide when water levels are rising, while ebb tide is the outgoing tide when water levels are falling. This movement is crucial for navigation and anchoring.',
            nauticalConcepts: 'Tide Movement:\n• Flood Tide: Rising water level\n• Ebb Tide: Falling water level\n• Slack Water: Period of minimal movement\n\nKey Terms:\n• High Water: Maximum tide level\n• Low Water: Minimum tide level\n• Tidal Stream: Water movement with tide',
            visualAidType: 'tide_cycle',
            visualAidData: '',
          ),
          Question(
            question: 'What is tidal range?',
            options: [
              'The speed of the tide',
              'The direction of the tide',
              'The difference between high and low tide',
              'The time between tides',
            ],
            correctAnswer: 2,
            explanation: 'Tidal range is the vertical difference between high tide and low tide levels.',
            aiExplanation: 'Tidal range is the vertical distance between high tide and low tide levels. This measurement is crucial for navigation, as it affects water depth, anchoring, and access to harbors and anchorages.',
            nauticalConcepts: 'Tidal Range:\n• Definition: Height difference between tides\n• Spring Range: Maximum difference\n• Neap Range: Minimum difference\n\nKey Terms:\n• Chart Datum: Reference level for depths\n• Height of Tide: Current water level\n• Under Keel Clearance: Space below boat',
            visualAidType: 'tide_cycle',
            visualAidData: '',
          ),
          Question(
            question: 'What is a tidal stream?',
            options: [
              'A river flowing into the sea',
              'The movement of water with the tide',
              'A type of wave',
              'A coastal current',
            ],
            correctAnswer: 1,
            explanation: 'A tidal stream is the horizontal movement of water that accompanies the rise and fall of the tide.',
            aiExplanation: 'Tidal streams are the horizontal movements of water that occur with the changing tide. These currents can significantly affect boat speed and course, and understanding them is essential for safe navigation.',
            nauticalConcepts: 'Tidal Streams:\n• Definition: Horizontal water movement\n• Direction: Changes with tide phase\n• Speed: Varies with tide strength\n\nKey Terms:\n• Set: Direction of tidal stream\n• Drift: Speed of tidal stream\n• Rate: Speed in knots',
            visualAidType: 'tide_cycle',
            visualAidData: '',
          ),
          Question(
            question: 'What is slack water?',
            options: [
              'Very fast tidal movement',
              'No tidal movement',
              'Wave movement',
              'Wind-driven current',
            ],
            correctAnswer: 1,
            explanation: 'Slack water is the period when there is little or no tidal movement, occurring between flood and ebb tides.',
            aiExplanation: 'Slack water is the period of minimal tidal movement that occurs between flood and ebb tides. This is often the best time for certain maritime operations, such as docking or crossing strong tidal streams.',
            nauticalConcepts: 'Slack Water:\n• Definition: Minimal tidal movement\n• Timing: Between tide changes\n• Duration: Varies by location\n\nKey Terms:\n• Stand: Period of minimal change\n• Tide Tables: Predict slack times\n• Safe Period: For navigation',
            visualAidType: 'tide_cycle',
            visualAidData: '',
          ),
        ],
      ),
    ),
    Quiz(
      title: 'Navigation Basics Quiz',
      description: 'Test your understanding of basic navigation concepts and techniques.',
      icon: Icons.map,
      questionCount: 5,
      screen: QuizSystem(
        title: 'Navigation Basics Quiz',
        description: 'Test your understanding of basic navigation concepts and techniques.',
        icon: Icons.map,
        questions: [
          Question(
            question: 'What is a chart datum?',
            options: [
              'The highest tide level', 
              'The lowest tide level',
              'The average tide level',
              'The current tide level'
            ],
            correctAnswer: 1,
            explanation: 'Chart datum is the lowest astronomical tide level used as the reference point for depths on nautical charts.',
            aiExplanation: 'Understanding chart datum is crucial for safe navigation:\n\n1. Definition:\n   - Lowest astronomical tide\n   - Reference point for depths\n   - Standardized worldwide\n\n2. Importance:\n   - Safe navigation\n   - Depth calculations\n   - Grounding prevention\n\n3. Practical Applications:\n   - Depth calculations\n   - Harbor entry planning\n   - Route planning\n\n4. Safety Considerations:\n   - Under-keel clearance\n   - Harbor access timing\n   - Alternative routes\n\n5. Navigation Planning:\n   - Tide calculations\n   - Route optimization\n   - Harbor selection',
            nauticalConcepts: 'Chart Datum:\n• Definition: Lowest astronomical tide\n• Purpose: Reference for depths\n• Usage: Safe navigation\n\nKey Terms:\n• LAT: Lowest Astronomical Tide\n• Depth: Measured from datum\n• Height: Above datum',
            visualAidType: 'navigation',
            visualAidData: '',
          ),
          Question(
            question: 'What is a bearing?',
            options: [
              'The distance to an object',
              'The direction to an object',
              'The height of an object',
              'The speed of an object',
            ],
            correctAnswer: 1,
            explanation: 'A bearing is the direction to an object, measured in degrees from true or magnetic north.',
            aiExplanation: 'A bearing is the direction to an object, measured in degrees from a reference point (usually true north or magnetic north). Bearings are essential for navigation, position fixing, and course plotting.',
            nauticalConcepts: 'Bearings:\n• Definition: Direction to an object\n• Types: True, Magnetic, Relative\n• Measurement: Degrees from north\n\nKey Terms:\n• True Bearing: From true north\n• Magnetic Bearing: From magnetic north\n• Relative Bearing: From boat\'s heading',
            visualAidType: 'navigation',
            visualAidData: '',
          ),
          Question(
            question: 'What is a waypoint?',
            options: [
              'A type of compass',
              'A position on a chart',
              'A type of buoy',
              'A navigation light',
            ],
            correctAnswer: 1,
            explanation: 'A waypoint is a specific position on a chart, defined by coordinates, used for navigation and route planning.',
            aiExplanation: 'Waypoints are essential for modern navigation:\n\n1. Definition:\n   - Specific position\n   - Defined coordinates\n   - Navigation reference\n\n2. Uses:\n   - Route planning\n   - Position marking\n   - Course following\n\n3. Types:\n   - Pre-planned\n   - User-defined\n   - Chart features\n\n4. Practical Applications:\n   - GPS navigation\n   - Route optimization\n   - Position marking\n\n5. Safety Benefits:\n   - Course verification\n   - Position tracking\n   - Emergency reference',
            nauticalConcepts: 'Waypoints:\n• Definition: Specific position on chart\n• Uses: Route planning, navigation\n• Types: Pre-planned, user-defined\n\nKey Terms:\n• Coordinates: Position reference\n• GPS: Global Positioning System\n• Route: Series of waypoints',
            visualAidType: 'navigation',
            visualAidData: '',
          ),
          Question(
            question: 'What is dead reckoning?',
            options: [
              'Using GPS navigation',
              'Calculating position based on course and speed',
              'Using radar navigation',
              'Following a marked channel',
            ],
            correctAnswer: 1,
            explanation: 'Dead reckoning is calculating a vessel\'s position based on its course, speed, and time from a known position.',
            aiExplanation: 'Dead reckoning is a fundamental navigation technique:\n\n1. Definition:\n   - Position calculation\n   - Based on movement\n   - From known position\n\n2. Components:\n   - Course\n   - Speed\n   - Time\n\n3. Practical Uses:\n   - Position estimation\n   - Course planning\n   - Navigation backup\n\n4. Limitations:\n   - Current effects\n   - Wind effects\n   - Instrument errors\n\n5. Safety Considerations:\n   - Regular updates\n   - Error accumulation\n   - Alternative methods',
            nauticalConcepts: 'Dead Reckoning:\n• Definition: Position calculation\n• Components: Course, Speed, Time\n• Uses: Position estimation\n\nKey Terms:\n• Course: Direction of travel\n• Speed: Rate of movement\n• Time: Duration of travel',
            visualAidType: 'navigation',
            visualAidData: '',
          ),
          Question(
            question: 'What is a transit?',
            options: [
              'A type of compass',
              'Two objects in line',
              'A navigation light',
              'A type of buoy',
            ],
            correctAnswer: 1,
            explanation: 'A transit is when two objects appear in line, used for position fixing and course following.',
            aiExplanation: 'Transits are valuable navigation tools:\n\n1. Definition:\n   - Two objects aligned\n   - Visual reference line\n   - Position indicator\n\n2. Uses:\n   - Position fixing\n   - Course following\n   - Harbor entry\n\n3. Types:\n   - Natural features\n   - Man-made objects\n   - Navigation marks\n\n4. Practical Applications:\n   - Harbor approaches\n   - Channel following\n   - Position verification\n\n5. Safety Benefits:\n   - Accurate navigation\n   - Course maintenance\n   - Position confirmation',
            nauticalConcepts: 'Transits:\n• Definition: Two objects in line\n• Uses: Position fixing, course following\n• Types: Natural, man-made\n\nKey Terms:\n• Range: Two objects in line\n• Leading Lights: Navigation aids\n• Position Fix: Location determination',
            visualAidType: 'navigation',
            visualAidData: '',
          ),
        ],
      ),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              kDeepBlue,
              kOceanBlue,
            ],
          ),
        ),
        child: SafeArea(
          child: Column(
            children: [
              // App Bar
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: kBackgroundColor,
                  borderRadius: const BorderRadius.only(
                    bottomLeft: Radius.circular(20),
                    bottomRight: Radius.circular(20),
                  ),
                ),
                child: Row(
                  children: [
                    IconButton(
                      icon: Icon(Icons.arrow_back, color: kWhite),
                      onPressed: () => Navigator.pop(context),
                    ),
                    const SizedBox(width: 8),
                    Text(
                      'Quizzes',
                      style: TextStyle(
                        color: kWhite,
                        fontSize: 24,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
              // Main Content
              Expanded(
                child: ListView.builder(
                  padding: const EdgeInsets.all(16),
                  itemCount: quizzes.length,
                  itemBuilder: (context, index) {
                    final quiz = quizzes[index];
                    return Container(
                      margin: const EdgeInsets.only(bottom: 16),
                      decoration: BoxDecoration(
                        color: kBackgroundColor,
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(
                          color: kBorderColor,
                          width: 1,
                        ),
                      ),
                      child: Material(
                        color: Colors.transparent,
                        child: InkWell(
                          onTap: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(builder: (context) => quiz.screen),
                            );
                          },
                          borderRadius: BorderRadius.circular(20),
                          child: Padding(
                            padding: const EdgeInsets.all(16),
                            child: Row(
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(12),
                                  decoration: BoxDecoration(
                                    color: kBorderColor,
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: Icon(
                                    quiz.icon,
                                    color: kWhite,
                                    size: 32,
                                  ),
                                ),
                                const SizedBox(width: 16),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        quiz.title,
                                        style: TextStyle(
                                          color: kWhite,
                                          fontSize: 18,
                                          fontWeight: FontWeight.bold,
                                        ),
                                      ),
                                      const SizedBox(height: 4),
                                      Text(
                                        quiz.description,
                                        style: TextStyle(
                                          color: kTextColor,
                                          fontSize: 14,
                                        ),
                                      ),
                                      const SizedBox(height: 8),
                                      Container(
                                        padding: const EdgeInsets.symmetric(
                                          horizontal: 8,
                                          vertical: 4,
                                        ),
                                        decoration: BoxDecoration(
                                          color: kBorderColor,
                                          borderRadius: BorderRadius.circular(12),
                                        ),
                                        child: Text(
                                          '${quiz.questionCount} questions',
                                          style: TextStyle(
                                            color: kWhite,
                                            fontSize: 12,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                Icon(
                                  Icons.arrow_forward_ios,
                                  color: kTextColor,
                                  size: 16,
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
} 